settings:
  - path: task_dirs
    initialization_description: Where can tasks be loaded from?
    strategy: merge
    init: true
    type: path
    is_project: false
    values:
      - src/SprykerSdk/Sdk/Extension/Tasks
  - path: setting_dirs
    initialization_description: Where can settings be loaded from?
    strategy: merge
    init: true
    type: path
    is_project: false
    values:
      - src/SprykerSdk/Sdk/Extension/Settings
  - path: value_resolver_dirs
    initialization_description: Where can value resolvers be loaded from?
    strategy: merge
    init: true
    type: path
    is_project: false
    values:
      - src/SprykerSdk/Sdk/Extension/ValueResolvers
  - path: sdk_dir
    initialization_description: Where is the sdk directory?
    strategy: overwrite
    init: true
    is_project: false
    type: path
    values: './'
  - path: report_usage_statistics
    initialization_description: Do you agree to send anonymous usage reports to help improving the SDK?
    strategy: overwrite
    init: true
    is_project: true
    type: boolean
    values: false
  - path: coreNamespaces
    initialization_description: Do you approve core namespaces?
    strategy: merge
    init: false
    is_project: true
    type: string
    values:
        - SprykerShop
        - SprykerEco
        - Spryker
        - SprykerSdk
  - path: projectNamespaces
    initialization_description: Do you approve project namespaces?
    strategy: merge
    init: false
    is_project: true
    type: string
    values:
        - Pyz
  - path: projectNamespace
    initialization_description: Do you approve project namespace?
    strategy: merge
    init: false
    is_project: true
    type: string
    values: Pyz
