---
id: "acp:translation:validate"
short_description: "Validate ACP translation file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/acp app:translation:validate %translation-file% %manifest-path% %configuration-file%"
type: local_cli
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%translation-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "translation-file"
      description: "Path to translation file"
      type: string
  - name: "%manifest-path%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "manifest-path"
      description: "Path to manifest file"
      type: string
  - name: "%configuration-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "configuration-file"
      description: "Path to configuration file"
      type: string
