---
id: "acp:openapi:create"
short_description: "Create ACP OpenAPI file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/syncapi schema:openapi:create %openapi-file% %api-version% %title% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%title%"
    value_resolver: STATIC_TEXT
    optional: false
    configuration:
      name: "title"
      description: "The name of the App"
      type: string
  - name: "%openapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "openapi-file"
      description: "Path to save OpenAPI file to"
      type: string
  - name: "%api-version%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "api-version"
      description: "Version number of the OpenAPI schema"
      type: string
