---
id: "acp:asyncapi:generate"
short_description: "Generate ACP AsyncAPI code."
help: ~
stage: build
version: 0.1.0
command: "INSTALLED_ROOT_DIRECTORY=%sdk_dir% php %sdk_dir%/vendor/bin/asyncapi code:asyncapi:generate %asyncapi-file% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%asyncapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "asyncapi-file"
      description: "Path to AsyncAPI file [default: 'config/api/asyncapi/asyncapi.yml']"
      type: string
  - name: "%organization%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "organization"
      description: "Namespace that should be used for the code builder. When set to Spryker code will be generated in the core modules. [default: 'App']"
      type: string
