---
id: "acp:asyncapi:message-add"
short_description: "Create ACP AsyncAPI file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/asyncapi schema:asyncapi:message:add %channel-name% %message-name% %operation-id% %asyncapi-file% %property% %from-transfer-class% %message-type% %add-metadata% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: '%message-type%'
    value_resolver: OPTION
    optional: false
    configuration:
      name: 'message-type'
      choiceValues: ['publish', 'subscribe']
      description: 'Select event type for a message'
  - name: '%add-metadata%'
    value_resolver: FLAG
    optional: true
    configuration:
      name: 'add-metadata'
      defaultValue: true
      type: boolean
      description: 'When this option is set the defined default set of metadata will be added to the message definition'
  - name: "%from-transfer-class%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "from-transfer-class"
      description: "The Transfer class name from which the message should be created"
      type: string
  - name: "%operation-id%"
    value_resolver: STATIC_TEXT
    optional: false
    configuration:
      name: "operation-id"
      description: "Operation ID of the message. Operation ID is required for each message"
      type: string
  - name: "%message-name%"
    value_resolver: STATIC_TEXT
    optional: false
    configuration:
      name: "message-name"
      description: "The message name"
      type: string
  - name: "%channel-name%"
    value_resolver: STATIC_TEXT
    optional: false
    configuration:
      name: "channel-name"
      description: "Channel name for message"
      type: string
  - name: "%asyncapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "asyncapi-file"
      description: "Path to save AsyncAPI file to"
      type: string
  - name: "%property%"
    value_resolver: ARRAY_OPTION
    optional: false
    configuration:
      name: "property"
      description: "When this option is set the property value will be added to the message definition of the specified channel. Example propertyA:valueA [enter for newline] propertyB:valueB"
      type: array
