---
id: "acp:openapi:generate"
short_description: "Generate ACP OpenAPI code."
help: ~
stage: build
version: 0.1.0
command: "INSTALLED_ROOT_DIRECTORY=%sdk_dir% php %sdk_dir%/vendor/bin/syncapi code:openapi:generate %project-root% %openapi-file% %application-type% %organization% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%project-root%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "project-root"
      description: "Relative path to project root"
      type: path
  - name: "%openapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "openapi-file"
      description: "Path to AsyncAPI file [default: 'config/api/openapi/openapi.yml']"
      type: string
  - name: "%organization%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "organization"
      description: "Namespace that should be used for the code builder. When set to Spryker code will be generated in the core modules. [default: 'App']"
      type: string
  - name: "%application-type%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "application-type"
      description: "Application type [default: 'backend']"
      type: string
