---
id: "acp:config:create"
short_description: "Create ACP configuration file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/acp app:configuration:create %configuration-file%"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%configuration-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "configuration-file"
      description: "Path to save configuration file to"
      type: string
