---
id: "aop:openapi:validate"
short_description: "Validate AOP OpenAPI file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/syncapi openapi:schema:validate %openapi-file% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%openapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "openapi-file"
      description: "Path to OpenAPI file"
      type: string
