---
id: 'validation:php:codestyle-fix'
short_description: 'Fixes violations and validates your php code using different approaches like codestyle. Generate report in the end.'
help: 'Fixes violations and validates your php code using different approaches like codestyle. Generate report in the end.'
stage: build
version: 1.0.0
command: ~
type: task_set
tasks:
  - id: 'violation:php:clean-report-dir'
    stop_on_error: false
  - id: 'validation:php:codestyle-check'
    stop_on_error: false
placeholders: []
