---
id: 'validation:php:codestyle'
short_description: 'Check your code by running a static code analysis'
help: ~
stage: build
version: 1.0.0
command: 'php %sdk_dir%/vendor/bin/phpcs --standard=%sdk_dir%/vendor/spryker/code-sniffer/Spryker/ruleset.xml --report=json ./%path%  --report-file=%reportDir%/phpcs.codestyle.json'
type: local_cli
placeholders:
    -   name: '%sdk_dir%'
        value_resolver: SDK_DIR
        optional: true
    -   name: '%path%'
        value_resolver: STATIC
        optional: false
        configuration:
            name: 'path'
            description: 'Relative path to module directory in project'
            type: path
            settingPaths: [ ]
    -   name: '%reportDir%'
        value_resolver: STATIC
        optional: true
        configuration:
            name: 'report_dir'
            description: 'Reports directory'
            type: string
            settingPaths: [ 'report_dir' ]
report_converter:
    name: CheckstyleViolationReportConverter
    configuration:
        input_file: phpcs.codestyle.json
        producer: phpcs
