---
id: "validation:php:benchmark"
short_description: "Check your code efficiency by running a benchmark"
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/phpbench run %tests% --bootstrap=%bootstrap% %iterations% %revs% %report% %time-unit%"
type: local_cli
optional: false
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%tests%"
    value_resolver: STATIC
    optional: true
    configuration:
      name: "tests"
      description: "Relative path to tests directory in project"
      type: path
  - name: "%bootstrap%"
    value_resolver: STATIC
    optional: false
    configuration:
      name: "bootstrap"
      description: "Relative path to bootstrap file in project"
      type: path
  - name: "%iterations%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "iterations"
      description: "Iterations count"
      type: string
      defaultValue: 1
  - name: "%revs%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "revs"
      description: "Revolution count"
      type: string
      defaultValue: 1
  - name: "%report%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "report"
      description: "Report config"
      type: string
      defaultValue: '"\"generator\":\"expression\",\"cols\":[\"benchmark\",\"subject\",\"best\",\"mean\",\"worst\",\"stdev\",\"revs\",\"its\"]"'
  - name: "%time-unit%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "time-unit"
      description: "Time unit"
      type: string
      defaultValue: milliseconds
