---
id: "validation:frontend:prettier"
short_description: "An opinionated code formatter"
help: ~
stage: build
version: 0.1.0
command: "npx prettier --check --loglevel=%log_level% ./%path% > %reportDir%/frontend.prettier.log 2>&1"
type: local_cli
placeholders:
  - name: "%reportDir%"
    value_resolver: STATIC
    optional: true
    configuration:
      name: "report_dir"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
  - name: "%path%"
    value_resolver: STATIC
    optional: false
    configuration:
      name: "path"
      description: "Relative path to module directory in project"
      type: path
      settingPaths: []
  - name: "%log_level%"
    value_resolver: STATIC
    optional: true
    configuration:
      name: "log_level"
      description: "What level of logs to report (possible values: log, error, warn)"
      help: "What level of logs to report (possible values: log, error, warn)"
      type: string
      defaultValue: log
      choiceValues:
        - log
        - error
        - warn
report_converter:
  name: PrettierSnifferViolationReportConverter
  configuration:
    input_file: frontend.prettier.log
    producer: prettier
