---
id: "validation:php:rector"
short_description: "Instant Upgrades and Automated Refactoring"
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/rector process ./%path% %config% %is-ansi%"
type: local_cli
optional: false
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%reportDir%"
    value_resolver: STATIC
    optional: true
    configuration:
      name: "report_dir"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
  - name: "%path%"
    value_resolver: STATIC
    optional: false
    configuration:
      name: "path"
      description: "Relative path to module directory in project"
      type: path
      defaultValue: "src"
  - name: "%config%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "config"
      description: "Path to config file"
      type: string
      defaultValue: "architector.php"
  - name: "%is-ansi%"
    value_resolver: FLAG
    optional: true
    configuration:
      name: "is-ansi"
      flag: "ansi"
      description: "Force ANSI output"
      type: string
      defaultValue: true
