---
id: "validation:scss:codestyle"
short_description: "Check your scss styles to avoid errors and enforce conventions"
help: ~
stage: build
version: 0.1.0
command: "node %sdk_dir%/frontend/libs/stylelint.js %file-path% %config-path% > %reportDir%/stylelint.codestyle.json"
type: local_cli
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%reportDir%"
    value_resolver: STATIC_TEXT
    optional: true
    configuration:
      name: "report_dir"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
  - name: "%file-path%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "file-path"
      description: "Execute stylelint only for this file"
      type: string
  - name: "%config-path%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: "config-path"
      description: "Use this stylelint config instead of default"
      type: string
report_converter:
  name: ScssLinterViolationReportConverter
  configuration:
    input_file: stylelint.codestyle.json
    producer: stylelint
