---
id: "validation:scss:codestyle"
short_description: "Check your scss styles to avoid errors and enforce conventions"
help: ~
stage: build
version: 0.1.0
command: "node %sdk_dir%/frontend/libs/stylelint.js > %reportDir%/stylelint.codestyle.json"
type: local_cli
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%reportDir%"
    value_resolver: STATIC
    optional: true
    configuration:
      name: "report_dir"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
report_converter:
  name: ScssLinterViolationReportConverter
  configuration:
    input_file: stylelint.codestyle.json
    producer: stylelint
