settings:
  - path: extension_dirs
    initialization_description: Where can extensions be loaded from?
    strategy: merge
    init: true
    type: path
    is_project: false
    values:
        - src/
        - extension/
  - path: sdk_dir
    initialization_description: Where is the sdk directory?
    strategy: overwrite
    init: true
    is_project: false
    type: path
    values: './'
  - path: project_dir
    initialization_description: Where is the project directory?
    strategy: overwrite
    init: true
    is_project: true
    type: path
    values: './'
  - path: report_usage_statistics
    initialization_description: Do you agree to send anonymous usage reports to help improving the SDK?
    strategy: overwrite
    init: true
    is_project: true
    type: boolean
    values: false
  - path: coreNamespaces
    initialization_description: Do you approve core namespaces?
    strategy: merge
    init: false
    is_project: true
    type: string
    values:
        - SprykerShop
        - SprykerEco
        - Spryker
        - SprykerSdk
  - path: projectNamespaces
    initialization_description: Do you approve project namespaces?
    strategy: merge
    init: false
    is_project: true
    type: string
    values:
        - Pyz
  - path: projectNamespace
    initialization_description: Do you approve project namespace?
    strategy: merge
    init: false
    is_project: true
    type: string
    values: Pyz
