doctrine:
    dbal:
        url: 'sqlite:///%kernel.project_dir%/var/data.db'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Sdk:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Resources/config/doctrine'
                prefix: 'SprykerSdk\Sdk\Infrastructure\Entity'
                alias: sdk
