coverage:
    range: 70..80
    round: nearest
    precision: 2

ignore:
    - "app"
    - "assets"
    - "bin"
    - "build"
    - "config"
    - "db"
    - "docs"
    - "frontend"
    - "infrastructure"
    - "public"
    - "Sniffs"
    - "translations"
    - "var"
    - "vendor"
    - "src/Core/Application/Dependency"
    - "src/Core/Application/DependencyInjection"
    - "src/Core/Application/Dto"
    - "src/Core/Application/Exception"
    - "src/Core/Application/Resources"
    - "src/Core/Domain"
    - "src/Core/SprykerSdkCoreBundle.php"
    - "src/Extension/DependencyInjection"
    - "src/Extension/Resources"
    - "src/Extension/SprykerSdkExtensionBundle.php"
    - "src/Infrastructure/DependencyInjection"
    - "src/Infrastructure/Dto"
    - "src/Infrastructure/Entity"
    - "src/Infrastructure/Event"
    - "src/Infrastructure/Exception"
    - "src/Infrastructure/Resources"
    - "src/Infrastructure/SprykerSdkInfrastructureBundle.php"
    - "src/Presentation/Console/DependencyInjection"
    - "src/Presentation/Console/Resources"
    - "src/Presentation/Ide/Dto"
    - "src/Presentation/RestApi/Enum"
    - "src/Presentation/RestApi/Exception"
    - "src/Presentation/RestApi/Resources"
    - "src/Presentation/RestApi/SprykerSdkRestApiBundle.php"
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.xml"
    - "**/*.lock"
