version: '3.0'

services:
    nginx:
        image: spryker/php-sdk-api-nginx:${SDK_VERSION:-latest}
        ports:
            - ${SDK_REST_API_PORT:-80}:80
        depends_on:
            - php-fpm
        restart: always

    php-fpm:
        image: spryker/php-sdk-api:${SDK_VERSION:-latest}
        restart: always
        environment:
            SDK_DIR: ${SDK_DIR}
            EXECUTABLE_FILE_PATH: ${EXECUTABLE_FILE_PATH}
            SPRYKER_XDEBUG_HOST_IP: ${SPRYKER_XDEBUG_HOST_IP:-}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
            APP_ENV: prod
            APP_DEBUG: 0
