version: '3.0'

services:
    nginx:
        image: spryker/php-sdk-api-nginx
        ports:
            - '8080:80'
        depends_on:
            - php-fpm
        restart: always

    php-fpm:
        image: spryker/php-sdk-api
        restart: always
        environment:
            APP_ENV: prod
            APP_DEBUG: 'true'
            TELEMETRY_ENABLED: 'false'
            TELEMETRY_TRANSPORT: file
            TELEMETRY_SERVER_URL: ''
            GITHUB_AUTH_METHOD: http_password
            GITHUB_USERNAME: username
            GITHUB_SECRET: password_or_token
            APPLICATION_ENV:    development
