SprykerSdk\Sdk\Infrastructure\Entity\RemovedEvent:
    type: entity
    repositoryClass: \SprykerSdk\Sdk\Infrastructure\Repository\RemovedEventRepository
    table: sdk_removed_event
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        commands:
            targetEntity: Command
            cascade: ["persist", "remove"]
            joinTable:
                name: sdk_removed_event_command
                joinColumns:
                    removed_event_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    command_id:
                        referencedColumnName: id
                        unique: true
                        onDelete: CASCADE
        placeholders:
            targetEntity: Placeholder
            cascade: ["persist", "remove"]
            joinTable:
                name: sdk_removed_event_placeholder
                joinColumns:
                    removed_event_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    placeholder_id:
                        referencedColumnName: id
                        unique: true
                        onDelete: CASCADE
        files:
            targetEntity: File
            cascade: ["persist", "remove"]
            joinTable:
                name: sdk_removed_event_file
                joinColumns:
                    removed_event_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    file_id:
                        referencedColumnName: id
                        unique: true
                        onDelete: CASCADE
