---
id: "acp:openapi:validate"
short_description: "Validate ACP OpenAPI file."
help: ~
stage: build
version: 0.2.1
command: "php %sdk_dir%/vendor/bin/syncapi schema:openapi:validate %openapi-file% -v"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%openapi-file%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: "openapi-file"
      option: "openapi-file"
      description: "Path to OpenAPI file"
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
