---
id: "acp:asyncapi:generate"
short_description: "Generate ACP AsyncAPI code."
help: ~
stage: build
version: 0.2.1
command: "INSTALLED_ROOT_DIRECTORY=%sdk_dir% php %sdk_dir%/vendor/bin/asyncapi code:asyncapi:generate %asyncapi-file% -v"
type: local_cli_interactive
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%asyncapi-file%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: "asyncapi-file"
      option: "asyncapi-file"
      description: "Path to AsyncAPI file"
      type: string
