---
id: "acp:asyncapi:full-flow"
short_description: "Create ACP AsyncAPI"
help: ~
stage: build
version: 1.0.0
command: ~
type: task_set
tasks:
  - id: "acp:asyncapi:create"
    stop_on_error: true
  - id: "acp:asyncapi:message-add"
    stop_on_error: true
  - id: "acp:asyncapi:validate"
    stop_on_error: true
  - id: "acp:asyncapi:generate"
    stop_on_error: true
placeholders: []
shared_placeholders:
    '%sdk_dir%': ~
    '%asyncapi-file%': ~

