---
id: "acp:manifest:create"
short_description: "Create ACP manifest file."
help: ~
stage: build
version: 0.2.3
command: "php %sdk_dir%/vendor/bin/acp app:manifest:create %name% %locale%"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI_INTERACTIVE
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%name%"
    value_resolver: STATIC
    optional: false
    configuration:
      alias: "name"
      description: "The name of the App"
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
  - name: "%locale%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: "locale"
      description: "A valid locale e.g.: en_US"
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
      defaultValue: "en_US"
