---
id: "acp:asyncapi:validate"
short_description: "Validate ACP AsyncAPI file."
help: ~
stage: build
version: 0.1.0
command: "php %sdk_dir%/vendor/bin/asyncapi schema:asyncapi:validate %asyncapi-file% -v"
type: local_cli
placeholders:
  - name: "%sdk_dir%"
    value_resolver: SDK_DIR
    optional: true
  - name: "%asyncapi-file%"
    value_resolver: OPTION
    optional: true
    configuration:
        name: "asyncapi-file"
        description: "Path to AsyncAPI file"
        type: string
