---
id: "acp:asyncapi:create-full"
short_description: "Create ACP AsyncAPI file with message"
help: ~
stage: build
version: 1.0.0
command: ~
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TASK_SET_TYPE
tasks:
  - id: "acp:asyncapi:create"
    stop_on_error: true
  - id: "acp:asyncapi:message-add"
    stop_on_error: false
placeholders: []
shared_placeholders:
    '%sdk_dir%': ~
    '%asyncapi-file%':
        description: "Path to AsyncAPI file"
