---
id: "pbc:validate:run"
short_description: "Validates your php code using different approaches like codestyle, architecural and static analysis"
help: "Validates your php code using different approaches like codestyle, architecural and static analysis"
stage: build
version: 0.3.1
command: ~
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_TASK_SET
tasks:
  - id: "validation:php:codestyle-fix"
    stop_on_error: true
    placeholder_overrides:
        '%executable_command%':
            name: "%executable_command_codestyle_fix%"
  - id: "validation:php:codestyle-check"
    stop_on_error: true
    placeholder_overrides:
        '%executable_command%':
            name: "%executable_command_codestyle_check%"
        '%reportDir%':
            name: "%reportDir_codestyle_check%"
  - id: "validation:php:static"
    stop_on_error: true
    placeholder_overrides:
        '%reportDir%':
            name: "%reportDir_static%"
  - id: "validation:php:architecture"
    stop_on_error: true
    placeholder_overrides:
        '%config%':
            name: "%config_architecture%"
        '%executable_command%':
            name: "%executable_command_architecture%"
        '%reportDir%':
            name: "%reportDir_architecture%"
  - id: "tests:sdk:codecept"
    stop_on_error: true
    placeholder_overrides:
        '%executable_command%':
            name: "%executable_command_codecept%"
        '%reportDir%':
            name: "%reportDir_codecept%"
  - id: "validation:php:rector"
    stop_on_error: true
    placeholder_overrides:
        '%config%':
            name: "%config_rector%"
        '%executable_command%':
            name: "%executable_command_rector%"
        '%reportDir%':
            name: "%reportDir_rector%"
placeholders: []
shared_placeholders:
    '%sdk_dir%': ~
    '%severity%': ~
    '%path%': ~
