---
id: "pbc:validate"
short_description: "Validates your php code using different approaches like codestyle, architecural and static analysis"
help: "Validates your php code using different approaches like codestyle, architecural and static analysis"
stage: build
version: 0.2.0
command: ~
type: task_set
tasks:
  - id: "validation:php:codestyle-fix"
    stop_on_error: true
  - id: "validation:php:codestyle-check"
    stop_on_error: true
  - id: "validation:php:static"
    stop_on_error: true
  - id: "validation:php:architecture"
    stop_on_error: true
    placeholder_overrides:
        '%config%':
            name: "%phpmd_config%"
            value_resolver: CONFIG_PATH
            optional: true
            configuration:
                param: "config"
                name: "config"
                description: "Path to architecture validation config file"
                defaultValue: "vendor/spryker/architecture-sniffer/src/ruleset.xml"
  - id: "tests:sdk:codecept"
    stop_on_error: true
  - id: "validation:php:rector"
    stop_on_error: true
    placeholder_overrides:
        '%config%':
            name: "%rector_config%"
            value_resolver: OPTION
            optional: true
            configuration:
                param: "config"
                name: "config"
                description: "Path to rector validation config file"
                type: string
                defaultValue: "architector.php"
placeholders: []
shared_placeholders:
    '%sdk_dir%': ~
    '%severity%': ~
    '%path%': ~
    '%reportDir%': ~
