---
id: 'validation:frontend:eslint'
short_description: 'Check your javascript code to avoid errors and enforce conventions.'
help: ~
stage: build
version: 0.2.0
command: 'npx %prefix% %sdk_dir% eslint %config% %file% %fix% %output-format% %reportDir%'
type: local_cli
placeholders:
  - name: '%sdk_dir%'
    value_resolver: SDK_DIR
    optional: true
  - name: '%prefix%'
    value_resolver: FLAG
    optional: true
    configuration:
     flag: "prefix"
     defaultValue: true
  - name: "%reportDir%"
    value_resolver: REPORT_DIR
    optional: true
    configuration:
      option: "output-file"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
      defaultValue: "eslint.codestyle.json"
  - name: '%config%'
    value_resolver: STATIC
    optional: true
    configuration:
      option: 'config'
      name: 'config'
      description: 'Path to configuration file. By default uses .eslint.* config from current directory.'
      type: string
      defaultValue: null
  - name: '%fix%'
    value_resolver: FLAG
    optional: true
    configuration:
      alias: 'fix'
      description: 'Automatically fixes found problems.'
  - name: '%file%'
    value_resolver: STATIC
    optional: true
    configuration:
      type: path
      name: 'file'
      description: 'Full path to file.'
      defaultValue: 'src/**/*.{js,ts,jsx,tsx,html,vue}'
  - name: "%output-format%"
    value_resolver: STATIC
    optional: true
    configuration:
      option: "format"
      description: "Output format"
      type: string
      defaultValue: 'json'
report_converter:
  name: ESLintViolationReportConverter
  configuration:
    input_file: eslint.codestyle.json
    producer: eslint
