---
id: "pbc:validation:php:codestyle-fix"
short_description: "Check your code by running a static code analysis"
help: "You may need to set default phpcs standard before using it. By default uses phpcs.xml from the project root."
stage: build
version: 1.0.0
command: "php ./vendor/bin/phpcbf %severity% ./%path%"
type: local_cli
optional: true
placeholders:
  - name: "%severity%"
    value_resolver: OPTION
    optional: true
    configuration:
      name: 'severity'
      description: 'Severity level of the CodeSniffer'
  - name: "%path%"
    value_resolver: STATIC
    optional: false
    configuration:
      name: "path"
      description: "Relative path to module directory in project"
      type: path
      settingPaths: []
      defaultValue: 'src'
