---
id: "pbc:validation:php:codestyle-check"
short_description: "Check your code by running a static code analysis and generate report with violations"
help: "You may need to set default phpcs standard before using it. By default uses phpcs.xml from the project root."
stage: build
version: 1.0.0
command: "php ./vendor/bin/phpcs %severity% %path%"
type: local_cli
placeholders:
  - name: "%path%"
    value_resolver: STATIC
    optional: false
    configuration:
      alias: "path"
      description: "Relative path to module directory in project"
      type: path
      defaultValue: 'src'
  - name: "%severity%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: 'severity'
      option: 'severity'
      description: 'Severity level of the CodeSniffer'
