---
id: "validation:php:architecture"
short_description: "Check the architectural correctness of your code"
help: ~
stage: debug
version: 1.1.0
command: "%executable_command% %path% %format% %config% %strict% %minimum-priority% %priority% %reportDir%"
type: local_cli
placeholders:
  - name: "%executable_command%"
    value_resolver: PRIORITY_PATH
    optional: true
    configuration:
      description: "Executable folder (uses the first existing path)"
      defaultValue: "vendor/bin/phpmd"
      settingPaths: [ "project_dir", "sdk_dir" ]
  - name: "%format%"
    value_resolver: STATIC
    optional: true
    configuration:
      description: "Output format."
      type: path
      defaultValue: 'json'
  - name: "%path%"
    value_resolver: STATIC
    optional: true
    configuration:
      alias: "path"
      description: "Relative path to module directory in project"
      type: path
      defaultValue: 'src'
  - name: "%strict%"
    value_resolver: FLAG
    optional: false
    configuration:
      alias: "strict"
      description: "Report silent violations"
      defaultValue: false
  - name: "%minimum-priority%"
    value_resolver: FLAG
    optional: false
    configuration:
      alias: "minimum-priority"
      description: "Minimum priority"
      defaultValue: true
  - name: "%config%"
    value_resolver: CONFIG_PATH
    optional: true
    configuration:
      option: "config"
      alias: "config"
      description: "Config file"
      defaultValue: "vendor/spryker/architecture-sniffer/src/ruleset.xml"
  - name: "%priority%"
    value_resolver: STATIC
    optional: false
    configuration:
      alias: "priority"
      description: "Minimal PHPMD priority of rules to fail the validation"
      defaultValue: 2
      type: int
  - name: "%reportDir%"
    value_resolver: REPORT_DIR
    optional: true
    configuration:
      option: "reportfile"
      description: "Reports directory"
      type: string
      settingPaths: ["report_dir"]
      defaultValue: "phpmd.static.json"
report_converter:
  name: PHPMDViolationConverter
  configuration:
    input_file: phpmd.static.json
    producer: phpmd
