---
id: "validation:php:architecture"
short_description: "Check the architectural correctness of your code"
help: ~
stage: debug
version: 1.1.3
command: "%executable_command% %path% %format% %config% %strict% %minimum-priority% %priority%  %reportDir%"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI
placeholders:
  - name: "%executable_command%"
    value_resolver: PRIORITY_PATH
    optional: true
    configuration:
      description: "Executable folder (uses the first existing path)"
      defaultValue: "vendor/bin/phpmd"
      settingPaths: [ !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_PROJECT_DIR, !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_SDK_DIR ]
  - name: "%format%"
    value_resolver: STATIC
    optional: true
    configuration:
      description: "Output format."
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_PATH
      defaultValue: 'json'
  - name: "%path%"
    value_resolver: PRIORITY_PATH
    optional: true
    configuration:
      alias: "path"
      description: "Relative path to module directory in project"
      settingPaths: [ !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_PROJECT_DIR, !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_SDK_DIR ]
      defaultValue: 'src'
  - name: "%strict%"
    value_resolver: FLAG
    optional: false
    configuration:
      alias: "strict"
      description: "Report silent violations"
      defaultValue: false
  - name: "%minimum-priority%"
    value_resolver: FLAG
    optional: true
    configuration:
      alias: "minimum-priority"
      description: "Minimum priority"
      defaultValue: true
  - name: "%config%"
    value_resolver: PRIORITY_PATH
    optional: true
    configuration:
      alias: "config"
      description: "Config file"
      defaultValue: "vendor/spryker/architecture-sniffer/src/ruleset.xml"
      settingPaths: [ !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_PROJECT_DIR, !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_SDK_DIR ]
  - name: "%priority%"
    value_resolver: STATIC
    optional: false
    configuration:
      alias: "priority"
      description: "Minimal PHPMD priority of rules to fail the validation"
      defaultValue: 2
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_INT
  - name: "%reportDir%"
    value_resolver: REPORT_DIR
    optional: true
    configuration:
      option: "reportfile"
      description: "Reports directory"
      type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
      settingPaths: [!php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_REPORT_DIR]
      defaultValue: "phpmd.static.json"
report_converter:
  name: PHPMDViolationConverter
  configuration:
    input_file: phpmd.static.json
    producer: phpmd
