---
id: "project:install:run"
short_description: "Runs Sprykers install command."
help: ~
stage: build
version: 0.3.0
command: "php ./vendor/bin/install"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI
