---
id: "spryk:run"
short_description: "Runs a Spryk build process."
version: "0.1.0"
command: "php %executable_command% %spryk% %targetModule% %dependentModule% %option%"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI_INTERACTIVE
placeholders:
    - name: "%executable_command%"
      value_resolver: PRIORITY_PATH
      optional: true
      configuration:
          description: "Executable folder (uses the first existing path)"
          defaultValue: "vendor/bin/spryk-run"
          settingPaths: [ !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_SDK_DIR ]
    - name: "%spryk%"
      value_resolver: STATIC
      optional: false
      configuration:
          alias: 'spryk'
          description: 'Name of the Spryk which should be build.'
          type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
    - name: "%targetModule%"
      value_resolver: STATIC
      optional: true
      configuration:
          alias: 'targetModule'
          description: 'Name of the target module in format "[Organization.]ModuleName[.LayerName]".'
          type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
    - name: "%dependentModule%"
      value_resolver: STATIC
      optional: true
      configuration:
          alias: 'dependentModule'
          description: 'Name of the dependent module in format "[Organization.]ModuleName[.LayerName]".'
          type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_STRING
    - name: "%option%"
      value_resolver: STATIC
      optional: true
      configuration:
          alias: 'option'
          description: "Spryk-specific option"
          type: !php/const SprykerSdk\SdkContracts\Enum\ValueTypeEnum::TYPE_ARRAY
