---
id: "spryk:build"
short_description: "Builds a cache for all possible Spryk arguments. This command must only be used if a new argument was supplied."
version: "0.1.0"
command: "php %executable_command%"
type: !php/const SprykerSdk\SdkContracts\Enum\Task::TYPE_LOCAL_CLI
placeholders:
    - name: "%executable_command%"
      value_resolver: PRIORITY_PATH
      optional: true
      configuration:
        description: "Executable folder (uses the first existing path)"
        defaultValue: "vendor/bin/spryk-build"
        settingPaths: [ !php/const SprykerSdk\SdkContracts\Enum\Setting::PATH_SDK_DIR ]
