SprykerSdk\Sdk\Infrastructure\Entity\Task:
  type: entity
  repositoryClass: \SprykerSdk\Sdk\Infrastructure\Repository\TaskRepository
  table: sdk_task
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    shortDescription:
      type: string
      unique: false
      nullable: false
    help:
      type: string
      unique: false
      nullable: true
    version:
      type: string
      unique: false
      nullable: false
    successor:
      type: string
      unique: false
      nullable: true
    isDeprecated:
      type: boolean
      unique: false
      nullable: false
      default: false
  oneToMany:
    commandCollection:
      targetEntity: Command
      mappedBy: task
      cascade: ["persist", "remove"]
    placeholderCollection:
      targetEntity: Placeholder
      mappedBy: task
      cascade: ["persist", "remove"]
  oneToOne:
    lifecycle:
      targetEntity: Lifecycle
      cascade: ["persist", "remove"]
      joinColumn:
        name: lifecycle_id
        referencedColumnName: id
        onDelete: CASCADE
