parameters:
    env(ORGANIZATION_NAME): "spryker"
    env(REPOSITORY_NAME): "spryker-sdk"
services:
    logger_transaction_name_new_relic_processor:
        class: SprykerSdk\Sdk\Infrastructure\Logger\TransactionNameNewRelicProcessor
        arguments: [ '%env(ORGANIZATION_NAME)%/%env(REPOSITORY_NAME)%' ]
        tags:
            - { name: monolog.processor, handler: newrelic }
