project_dir: /home/veselov/PhpstormProjects/suite-nonsplit
project_namespace: Pyz
report_usage_statistics: false
value_resolver_dirs:
    - ./src/Task/ValueResolver/Value
task_dirs:
    - ./config/tasks
