services:
    api_doc.open_api_describer_helper:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\OpenApiDescriberHelper

    api_doc.sdk_commands_describer:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\SdkCommandsDescriber
        tags: [ 'nelmio_api_doc.describer' ]
        arguments:
            - !tagged_iterator 'rest_api.expose_command_api_doc'
            - !tagged_iterator 'console.command'
            - '@request_stack'
            - '@router.default'
            - '@api_doc.open_api_describer_helper'

    api_doc.task_describer:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\RunTaskDescriber
        tags: [ 'nelmio_api_doc.describer' ]
        arguments:
            - '@console.command_loader'
            - '@task_persistence_repository'
            - '@api_doc.open_api_describer_helper'
