services:

    _instanceof:
        SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\BaseDescriber:
            calls:
                - [ 'setDescriberHelper', [ '@describer_helper' ] ]

    describer_helper:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\DescriberHelper

    api_doc.sdk_commands_describer:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\SdkCommandsDescriber
        tags: [ 'nelmio_api_doc.describer' ]
        arguments:
            - !tagged_iterator "rest_api.exposed_command"

    api_doc.task_describer:
        class: SprykerSdk\Sdk\Presentation\RestApi\ApiDoc\RunTaskDescriber
        tags: [ 'nelmio_api_doc.describer' ]
        arguments:
            - '@console.command_loader'
