services:
  file_finder:
    class: Symfony\Component\Finder\Finder
  event_logger_factory:
    class: SprykerSdk\Sdk\Infrastructure\Service\EventLoggerFactory
    arguments:
      - '@project_setting_repository'
  event_logger:
    class: SprykerSdk\Sdk\Infrastructure\Service\EventLogger
    factory: ['@event_logger_factory', 'createEventLogger']
  setting_repository:
    class: SprykerSdk\Sdk\Infrastructure\Repository\SettingRepository
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@path_resolver'
  project_setting_repository:
    class: SprykerSdk\Sdk\Infrastructure\Repository\ProjectSettingRepository
    arguments:
      - '@setting_repository'
      - '@yaml_parser'
      - '%project_settings_file%'
  yaml_parser:
    class: Symfony\Component\Yaml\Yaml
  task_repository:
    public: true
    class: SprykerSdk\Sdk\Infrastructure\Repository\TaskYamlRepository
    arguments:
      - '@setting_repository'
      - '@file_finder'
      - '@yaml_parser'
      - !tagged_iterator sdk.task
  process_helper:
    class: Symfony\Component\Console\Helper\ProcessHelper
  local_cli_command_runner:
    class: SprykerSdk\Sdk\Infrastructure\Service\LocalCliRunner
    tags: ['command.runner']
    arguments:
      - '@process_helper'
  php__command_runner:
    class: SprykerSdk\Sdk\Infrastructure\Service\PhpCommandRunner
    tags: ['command.runner']
  cli_value_receiver:
    class: SprykerSdk\Sdk\Infrastructure\Service\CliValueReceiver
    arguments:
      - '@question_helper'
  cli_value_receiver_setup_listener:
    class: SprykerSdk\Sdk\Infrastructure\Event\CliReceiverSetupListener
    tags:
      - { name: kernel.event_listener, event: console.command, method: beforeConsoleCommand }
    arguments:
      - '@cli_value_receiver'
  cli_runner_setup_listener:
    class: SprykerSdk\Sdk\Infrastructure\Event\CliRunnerSetupListener
    tags:
      - { name: kernel.event_listener, event: console.command, method: beforeConsoleCommand }
    arguments:
      - '@local_cli_command_runner'
  value_receiver:
    alias: 'cli_value_receiver'
  value_resolver_registry:
    class: SprykerSdk\Sdk\Infrastructure\Service\ValueResolverRegistry
    arguments:
      - '@setting_repository'
      - '@value_receiver'
      - !tagged_iterator sdk.value_resolver
      - '%kernel.project_dir%'

  mapper.command_mapper:
    class: SprykerSdk\Sdk\Infrastructure\Mapper\CommandMapper

  mapper.placeholder_mapper:
    class: SprykerSdk\Sdk\Infrastructure\Mapper\PlaceholderMapper

  mapper.task_mapper:
    class: SprykerSdk\Sdk\Infrastructure\Mapper\TaskMapper
    arguments:
      - '@mapper.command_mapper'
      - '@mapper.placeholder_mapper'

  task_persistence_repository:
    class: SprykerSdk\Sdk\Infrastructure\Repository\TaskRepository
    arguments:
      - '@mapper.task_mapper'
      - '@doctrine'

  service.task_initializer:
    class: SprykerSdk\Sdk\Infrastructure\Service\TaskInitializer
    arguments:
      - '@task_repository'
      - '@task_persistence_repository'
      - '@event_dispatcher'
