#!/bin/sh

if [ -f ./vendor/bin/phpcs ]
then
    ./vendor/bin/phpcs --colors -p -s --extensions=php --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml --ignore=/tests/_project/, src/ tests/ extension/
    if [ $? -ne 0 ]
    then
        printf "\n\t\033[1;31m[PHP-CS] Push Aborted\n\n\033[0m"

        return 1
    fi
fi
if [ -f ./vendor/bin/phpstan ]
then
    ./vendor/bin/phpstan analyze -l 8 src/
    if [ $? -ne 0 ]
    then
        printf "\n\t\033[1;31m[Phpstan] Aborted\n\n\033[0m"

        return 1
    fi
fi
if [ -f ./vendor/bin/codecept ]
then
    ./vendor/bin/codecept build && ./vendor/bin/codecept run unit
    if [ $? -ne 0 ]
    then
        printf "\n\t\033[1;31m[Codecept] Aborted\n\n\033[0m"

        return 1
    fi
fi
